version: '3'
services:
  app:
    container_name: hellhounds-api
    build: .
    image: hellhounds-api
    command: bash -c "rm -f tmp/pids/server.pid && tail -f /dev/null"
    volumes:
      - .:/home/developer/app
      - ~/.ssh/:/home/developer/.ssh
      - ~/.gitconfig:/home/developer/.gitconfig
    ports:
      - "3000:3000"
    environment:
      - HELLHOUNDS_FIREBASE_URL
    depends_on:
      - db
  db:
    image: postgres
    container_name: hellhounds-db
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"